version: '3.9'

services:
  app:
    restart: ${RESTARTER:-always}
    build:
      context: .
      args:
        CONFIG: ${CI_BUILD_NAME:-lint}
      dockerfile: Dockerfile${BUILDER_POSTFIX:-}
    volumes:
      - ./envs/.env.${CI_BUILD_NAME:-lint}:/app/.env
    ports:
      - '${EXPOSE_PORT:-3000}:3000'
